/*
 * DrawPanel.java
 *
 * Created on 08 Aralýk 2011 Perþembe, 18:46
 */

package java2d;

import java.awt.*;
import java.awt.geom.*;

/**
 *
 * @author  a
 */
public class DrawPanel extends javax.swing.JPanel {
    
    /** Creates new form DrawPanel */
    public DrawPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    public void paintComponent(Graphics g) {
Graphics2D g2d = (Graphics2D)g;
Ellipse2D.Double circle = new Ellipse2D.Double(15, 15, 90, 90);
Rectangle2D.Double square =
new Rectangle2D.Double(10, 10, 100, 100);
g2d.fill(circle);
g2d.draw(square);
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
