//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Maliyet_Hesaplama
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Model1Container : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Model1Container object using the connection string found in the 'Model1Container' section of the application configuration file.
        /// </summary>
        public Model1Container() : base("name=Model1Container", "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model1Container object.
        /// </summary>
        public Model1Container(string connectionString) : base(connectionString, "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model1Container object.
        /// </summary>
        public Model1Container(EntityConnection connection) : base(connection, "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Entity1> Entity1Set
        {
            get
            {
                if ((_Entity1Set == null))
                {
                    _Entity1Set = base.CreateObjectSet<Entity1>("Entity1Set");
                }
                return _Entity1Set;
            }
        }
        private ObjectSet<Entity1> _Entity1Set;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Entity1Set EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEntity1Set(Entity1 entity1)
        {
            base.AddObject("Entity1Set", entity1);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Entity1")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Entity1 : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Entity1 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="aD">Initial value of the AD property.</param>
        /// <param name="fiyat">Initial value of the Fiyat property.</param>
        /// <param name="olcum_birimi">Initial value of the Olcum_birimi property.</param>
        public static Entity1 CreateEntity1(global::System.Int32 id, global::System.String aD, global::System.String fiyat, global::System.String olcum_birimi)
        {
            Entity1 entity1 = new Entity1();
            entity1.Id = id;
            entity1.AD = aD;
            entity1.Fiyat = fiyat;
            entity1.Olcum_birimi = olcum_birimi;
            return entity1;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AD
        {
            get
            {
                return _AD;
            }
            set
            {
                OnADChanging(value);
                ReportPropertyChanging("AD");
                _AD = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AD");
                OnADChanged();
            }
        }
        private global::System.String _AD;
        partial void OnADChanging(global::System.String value);
        partial void OnADChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Fiyat
        {
            get
            {
                return _Fiyat;
            }
            set
            {
                OnFiyatChanging(value);
                ReportPropertyChanging("Fiyat");
                _Fiyat = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Fiyat");
                OnFiyatChanged();
            }
        }
        private global::System.String _Fiyat;
        partial void OnFiyatChanging(global::System.String value);
        partial void OnFiyatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Olcum_birimi
        {
            get
            {
                return _Olcum_birimi;
            }
            set
            {
                OnOlcum_birimiChanging(value);
                ReportPropertyChanging("Olcum_birimi");
                _Olcum_birimi = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Olcum_birimi");
                OnOlcum_birimiChanged();
            }
        }
        private global::System.String _Olcum_birimi;
        partial void OnOlcum_birimiChanging(global::System.String value);
        partial void OnOlcum_birimiChanged();

        #endregion
    
    }

    #endregion
    
}
